// app/vue/src/components/Markdown.vue
<template>
  <v-container v-html="rendered"></v-container>
</template>

<script lang="ts">
import Vue from "vue"
import markdown from "markdown-it"

const md = new markdown().disable("image")

export default Vue.extend({
  props: {
    source: {
      type: String,
    },
  },

  computed: {
    rendered() {
      return md.render(this.source)
    },
  },
})
</script>

// app/frontend/src/components/Markdown.tsx
import React from "react";
import MarkdownIt from "markdown-it";
import { Box, BoxProps } from "@material-ui/core";

const md = new MarkdownIt().disable("image");

interface MarkdownProps extends BoxProps {
  source: string;
}

export default function Markdown({ source, ...otherProps }: MarkdownProps) {
  return (
    <Box
      dangerouslySetInnerHTML={{ __html: md.render(source) }}
      {...otherProps}
    />
  );
}
